[ninja]
name = "ninja"
description = {
    en = "Firmware code for Ninja & Hybrid SIMA robots",
    sr = "Firmver za Ninja i Hybrid SIMA robote",
    "sr-Cyrl" = "Фирмвер за Нинџа и Хибрид СИМА роботе"
}
url = "https://github.com/rurrobotics/ninja"
tags = ["rust", "embassy"]

[electronics]
name = "electronics"
description = {
    en = "Hardware for all robots",
    sr = "Hadver za sve robote",
    "sr-Cyrl" = "Хардвер за све роботе"
}
url = "https://github.com/rurrobotics/electronics"
tags = ["altium"]

